services:
  mysql:
    # prep-study-assistant-mysql简称：ppsa-mysql
    container_name: ppsa-mysql
    image: mysql:8.0.39
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      TZ: ${TIMEZONE}
    secrets:
      - mysql_root_password
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
      --binlog_expire_logs_seconds=604800
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - prep-study-assistant
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -uroot -p$$(cat /run/secrets/mysql_root_password)" ]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure

  minio:
    container_name: ppsa-minio
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    command: server --console-address ":9001" /data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_password
      TZ: ${TIMEZONE}
    volumes:
      - minio_data:/data
    secrets:
      - minio_root_password
    networks:
      - prep-study-assistant
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  minio_root_password:
    file: ./minio_root_password.txt

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local

networks:
  prep-study-assistant:
    driver: bridge